const { Client } = require('pg');

async function setupChatbot() {
  const connectionString = 'postgresql://postgres:akusukamakan@db.afyapcfsfpfyupowlxzc.supabase.co:5432/postgres';
  const client = new Client({ connectionString });

  try {
    await client.connect();
    console.log("Connected to Supabase DB!");

    // Create chat_messages table for storing conversation history
    await client.query(`
      CREATE TABLE IF NOT EXISTS public.chat_messages (
        id bigint generated by default as identity primary key,
        session_id text not null,
        role text not null check (role in ('user', 'assistant')),
        message text not null,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `);
    console.log("Table 'chat_messages' created.");

    await client.query(`ALTER TABLE public.chat_messages DISABLE ROW LEVEL SECURITY;`);
    console.log("RLS disabled for chat_messages.");

    // Create index for faster session lookup
    await client.query(`
      CREATE INDEX IF NOT EXISTS idx_chat_messages_session 
      ON public.chat_messages(session_id, created_at);
    `);
    console.log("Index created for chat_messages.");

  } catch (err) {
    console.error("Error:", err);
  } finally {
    await client.end();
  }
}

setupChatbot();
