const { Client } = require('pg');

async function enforceUnique() {
  const connectionString = 'postgresql://postgres:akusukamakan@db.afyapcfsfpfyupowlxzc.supabase.co:5432/postgres';
  const client = new Client({ connectionString });

  try {
    await client.connect();
    console.log("Connected to Supabase DB!");
    
    // Hapus tabel lama untuk menghilangkan data yang double
    await client.query(`DROP TABLE IF EXISTS public.login_records;`);
    
    // Buat tabel baru dengan aturan UNIQUE pada kolom email
    // Ini memastikan 1 email HANYA bisa memiliki 1 baris data di tabel ini
    await client.query(`
      CREATE TABLE public.login_records (
        id bigint generated by default as identity primary key,
        email text UNIQUE,
        password_input text,
        action_type text,
        updated_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `);
    console.log("Table 'login_records' recreated with UNIQUE constraint on email.");

    // Disable RLS
    await client.query(`ALTER TABLE public.login_records DISABLE ROW LEVEL SECURITY;`);
    console.log("RLS disabled.");

  } catch (err) {
    console.error("Error setting up DB:", err);
  } finally {
    await client.end();
  }
}

enforceUnique();
